name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Make
      run: make
